In [6]:
import numpy as np
from numpy import random

rng = random.default_rng(23)

In [15]:
matrix = rng.normal(50,20,size=(3,3))
print(matrix)

[[ 34.66174242  49.09216524 106.34418033]
 [ 30.1465118   17.57716952  41.46381737]
 [ 86.13875961  90.70231024  25.68025474]]


In [16]:
exclude = (matrix < 40)
print(exclude)

[[ True False False]
 [ True  True False]
 [False False  True]]


In [18]:
print(matrix[exclude])

[34.66174242 30.1465118  17.57716952 25.68025474]


In [20]:
orig = matrix[exclude]
matrix[exclude] = np.nan

print(matrix)

[[         nan  49.09216524 106.34418033]
 [         nan          nan  41.46381737]
 [ 86.13875961  90.70231024          nan]]


In [24]:
new0 = np.nanmean(matrix, axis=0)
new1 = np.nanmean(matrix, axis=1)
print(new0)
print(new1)

[86.13875961 69.89723774 73.90399885]
[77.71817278 41.46381737 88.42053492]


In [40]:
tm = [[1,1,1],[3,3,3],[5,5,9]]

In [31]:
print(np.mean(tm,axis=0))

[3. 3. 3.]


In [41]:
print(np.median(np.absolute(tm - np.median(tm,axis=0)),axis=0))

[2. 2. 2.]
